Feature: Make st_trace controllable by signals.
This patch makes the st_trace script controllable by SIGUSR1.  This
is useful for integrating tracing into an automated script since
st_trace previously was controlled by human input ("Press Enter to
end tracing...").  The old method is still used by default.  Use '-s'
to make st_trace wait for SIGUSR1 to terminate tracing instead.

Note that you can send SIGUSR1 to st_trace with the following example
commands:
> pkill -SIGUSR1 st_trace
> kill -SIGUSR1 <PID for st_trace>

diff --git a/st_trace b/st_trace
--- a/st_trace
+++ b/st_trace
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+if [ "$1" == "-s" ]
+then
+  AUTO=1
+  shift
+fi
+
+PIDS=""
+
+# signal that we're done gathering data and clean up
+on_finish()
+{
+    echo "Ending Trace..."
+    kill $PIDS
+    wait $PIDS
+
+    exit 0
+}
+
+# register shutdown signal handler
+trap 'on_finish' SIGUSR1
+
 [ -z "$FTCAT" ] && FTCAT=ftcat
 [ -z "$FTDEV" ] && FTDEV=/home/litmus/log
 
@@ -21,7 +42,13 @@ do
     echo $! "> $TARGET [$?]"
 done
 
-echo "Press Enter to end tracing..."
-read
-kill $PIDS
-wait $PIDS
+if [[ $AUTO != 1 ]]
+then
+    echo "Press Enter to end tracing..."
+    read
+    on_finish
+else
+    # wait for SIGUSR1 to terminate
+    echo "Waiting for SIGUSR1 to end tracing..."
+    while [ 1 ]; do sleep 10; done
+fi
